name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Create .env file
      run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" > event_finder/.env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> event_finder/.env
        echo "TOKEN_URL=${{ secrets.TOKEN_URL }}" >> event_finder/.env
        echo "EVENTS_URL=${{ secrets.EVENTS_URL }}" >> event_finder/.env
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r event_finder/requirements.txt
    
    - name: Build executable
      run: pyinstaller event_finder/app.spec
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibraryEvents
        path: dist/LibraryEvents.exe 