name: Build Executable

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-24.04', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Create .env file
      run: |
        echo "CLIENT_ID=${{ vars.CLIENT_ID }}" > event_finder/.env
        echo "CLIENT_SECRET=${{ vars.CLIENT_SECRET }}" >> event_finder/.env
        echo "API_URL=${{ vars.API_URL }}" >> event_finder/.env

    - run: pip install -r event_finder/requirements.txt pyinstaller
    - run: pyinstaller event_finder/app.spec
    - uses: actions/upload-artifact@v4
      with:
        name: LibraryEvents-${{ matrix.os }}
        path: |
          ${{ startsWith(matrix.os, 'windows') && 'dist/LibraryEvents.exe' || '' }}
          ${{ startsWith(matrix.os, 'macos') && 'dist/LibraryEvents.app' || '' }}
          ${{ startsWith(matrix.os, 'ubuntu') && 'dist/LibraryEvents' || '' }}
